apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: kishanpeddaboina/my-app:tagVersion
      ports:
        - containerPort: 8080
